# Generated by Django 4.2.11 on 2024-12-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='namespace',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
